{
  "language": "android",
  "jdk": "oraclejdk8",
  "sudo": false,
  "android": {
    "components": [
      "platform-tools",
      "tools",
      "build-tools-26.1.0",
      "android-22",
      "android-26",
      "sys-img-armeabi-v7a-android-26",
    ]
  },
  "before_script": [
    "android list avd"
    "android list target"
    "echo no | android create avd --force -n test -t google_apis_playstore-26 --abi x86",
    "emulator -avd test -no-audio -no-window &",
    "android-wait-for-emulator",
    "adb shell input keyevent 82 &"
  ],
  "script": "./gradlew connectedAndroidTest",
}
