
language: android
sudo: false
dist: trusty
jdk: oraclejdk8

env:
  global:
    - ANDROID_SDK_ROOT=/opt/android
    - BUILDTOOLS=26.0.2

android:
  components:
    - tools
    - platform-tools
    - build-tools-$BUILDTOOLS
    - android-25
    - android-26
    - sys-img-armeabi-v7a-android-25

before_install:
  - mkdir ${ANDROID_SDK_ROOT}
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;$BUILDTOOLS" "extras;android;m2repository"
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-25"
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "system-images;android-25;google_apis;armeabi-v7a"
  - export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH
  - which avdmanager
  - echo no | avdmanager create avd --force --name test --package 'system-images;android-25;google_apis;armeabi-v7a'

before_script:
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell settings put secure location_providers_allowed gps,network
  - adb shell settings put global window_animation_scale 0
  - adb shell settings put global transition_animation_scale 0
  - adb shell settings put global animator_duration_scale 0
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest

